# Generated by Django 5.1.7 on 2025-03-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='province',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
