# Generated by Django 5.1.7 on 2025-03-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_institution_province_alter_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
