# Generated by Django 5.2.4 on 2025-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_institution_latitude_institution_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10),
            preserve_default=False,
        ),
    ]
