# Generated by Django 5.2.4 on 2025-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('population', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0.0, help_text='Area in square kilometers')),
                ('gdp', models.FloatField(default=0.0, help_text='Gross Domestic Product in USD')),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('names', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
