# Generated by Django 5.2.4 on 2025-08-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='example.country', verbose_name='Country'),
        ),
    ]
