# Generated by Django 5.2.4 on 2025-08-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_institution__country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
    ]
