# Generated by Django 5.2.4 on 2025-08-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_remove_institution_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='_country',
            new_name='country',
        ),
    ]
