# Generated by Django 5.2.4 on 2025-08-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_rename__country_institution_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='example.country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
