# Generated by Django 5.2.4 on 2025-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_alter_institution_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
