# Generated by Django 6.1.2 on 2026-10-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_country_continent_country_subregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('impact_factor', models.FloatField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='example.journal')),
            ],
            options={
                'ordering': ('journal', 'year'),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published', models.DateField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='example.journal')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
