# Generated by Django 6.1.1 on 2026-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcraft', '0016_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='aspect_ratio',
            field=models.FloatField(default=1.8, help_text='Aspect ratio (width / height)'),
        ),
    ]
