# Generated by Django 6.1.1 on 2026-10-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcraft', '0017_entry_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='aspect_ratio',
            field=models.FloatField(default=1.8),
        ),
    ]
